version: 2

sources:
  - name: snowflake_sample_data
    database: SNOWFLAKE_SAMPLE_DATA  
    description: "A sample database provided by snowflake"
    schema: TPCDS_SF10TCL  
    tables:
      - name: STORE_SALES
        description: "Details about the sales in the store"
  

 